package:
  name: pyobjc-framework-cocoa
  version: "3.1.1"

source:
  fn: pyobjc-framework-Cocoa-3.1.1.tar.gz
  url: https://pypi.python.org/packages/2f/cb/5e9b4465f50581dc4ea3190f9c430de8eed071bb58693263578369441ac4/pyobjc-framework-Cocoa-3.1.1.tar.gz
  md5: 2832205d33d88ea53289563bd61771cf
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyobjc-framework-cocoa = pyobjc-framework-cocoa:main
    #
    # Would create an entry point called pyobjc-framework-cocoa that calls pyobjc-framework-cocoa.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyobjc-core >=3.1.1

  run:
    - python
    - pyobjc-core >=3.1.1

test:
  # Python imports
  imports:
    - AppKit
    - Cocoa
    - CoreFoundation
    - Foundation
    - PyObjCTools

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pyobjc.sourceforge.net
  license: MIT License
  summary: 'Wrappers for the Cocoa frameworks on Mac OS X'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
